### ISSUE TITLE
Uninformative installation error on MacOS

### ISSUE THREAD

**Issue by samyuyagati** [bitcoin-core/secp256k1#973] opened 2021-09-09 23:07 UTC
I am trying to install from source on MacOS (Catalina, 10.15.6) as follows:

```
git clone https://github.com/bitcoin-core/secp256k1.git
cd secp256k1
./autogen.sh
./configure
```
I have installed the following dependencies using Homebrew (with my current version listed):
autoconf: 2.71
automake: 1.16.4
libtool: 2.4.6
pkg-config: 0.29.2
libffi: 3.3 (keg-only: couldn't symlink, but have added to path as recommended)
gmp: 6.2.1

However, running configure results in an "unexpected newline" error and the script doesn't complete. Here is the verbose output I get when I try to run the configure script:
```
checking build system type... x86_64-apple-darwin19.6.0
checking host system type... x86_64-apple-darwin19.6.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin19.6.0 file names to x86_64-apple-darwin19.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin19.6.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin19.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ar... /usr/bin/ar
checking for ranlib... /usr/bin/ranlib
checking for strip... /usr/bin/strip
**./configure: line 13153: syntax error near unexpected token `newline'
./configure: line 13153: `    '''**
```

I suspect this newline error is actually due to a missing dependency, but the error message is uninformative and doesn't help me figure out which packages to install. I've installed the packages that I could find listed as dependencies online, but that doesn't resolve or change the error. I would appreciate any help with completing the installation, or at least fixing the error message here. 

------------
If it's helpful, here is the output of autogen.sh (there don't seem to be any errors; I did have to run autoupdate and rerun autogen):
```
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
glibtoolize: copying file 'build-aux/m4/libtool.m4'
glibtoolize: copying file 'build-aux/m4/ltoptions.m4'
glibtoolize: copying file 'build-aux/m4/ltsugar.m4'
glibtoolize: copying file 'build-aux/m4/ltversion.m4'
glibtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:32: warning: AC_PROG_CC_C89 is obsolete; use AC_PROG_CC
configure.ac:35: warning: ac_ext=c
configure.ac:35: ac_cpp='$CPP $CPPFLAGS'
configure.ac:35: ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
configure.ac:35: ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
configure.ac:35: ac_compiler_gnu=$ac_cv_c_compiler_gnu
configure.ac:35: if test -n "$ac_tool_prefix"; then
configure.ac:35:   # Extract the first word of "${ac_tool_prefix}gcc", so it can be a program name with args.
configure.ac:35: set dummy ${ac_tool_prefix}gcc; ac_word=$2
configure.ac:35: { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
configure.ac:35: printf %s "checking for $ac_word... " >&6; }
configure.ac:35: if test ${ac_cv_prog_CC+y}
configure.ac:35: then :
configure.ac:35:   printf %s "(cached) " >&6
configure.ac:35: else $as_nop
configure.ac:35:   if test -n "$CC"; then
configure.ac:35:   ac_cv_prog_CC="$CC" # Let the user override the test.
configure.ac:35: else
configure.ac:35: as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
configure.ac:35: for as_dir in $PATH
configure.ac:35: do
configure.ac:35:   IFS=$as_save_IFS
configure.ac:35:   case $as_dir in #(((
configure.ac:35:     '' is m4_require'd but not m4_defun'd
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/programs.m4:41: _AC_CHECK_PROG is expanded from...
./lib/autoconf/programs.m4:101: AC_CHECK_PROG is expanded from...
./lib/autoconf/programs.m4:221: AC_CHECK_TOOL is expanded from...
configure.ac:30: AC_PROG_CC is expanded from...
configure.ac:35: the top level
configure.ac:11: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
```

**Comment by real-or-random** [comment] 2021-09-10 10:20
Hm, that long warning in `configure.ac:35` is very strange. Looks like some quoting issue. It tries to find a single symbol that is split over tens of lines  and in fact contains real code... So I don't think it's a dependency issue.

Do you use some non-standard shell or have some strange shell settings?

Apart from that, it's hard to debug from here. As I said, I think the root cause is somewhere during generation of `configure` already but still, can you attach the entire generated `configure` script?

**Comment by samyuyagati** [comment] 2021-09-10 22:20
I use bash and I don't think I have strange shell settings -- I was installing several other packages from source around the same time that use the same autogen+configure setup and didn't have problems with any of those. I've attached the generated configure script in text file form
[configure.txt](https://github.com/bitcoin-core/secp256k1/files/7146712/configure.txt)
. The error is at line 13153 in this file.

**Comment by real-or-random** [comment] 2021-09-12 15:24
This is very strange. The code around this line is 

```
  case $as_dir in #(((
    ''
 as_dir=./ ;;
    */) ;;
    *) as_dir=$as_dir/ ;;
  esac
```
but it should be
```
  case $as_dir in #(((
    '') as_dir=./ ;;
    */) ;;
    *) as_dir=$as_dir/ ;;
  esac
```

So, a there's a newline instead of a `)`. Maybe it helps to edit the script as dirty workaround.


According to the warning message output by `autoreconf` (in `autogen.sh`), there's something wrong deep in the internals of autoconf... 

I have no idea what's going on. Here's a shoot in the dark: Can you try to remove the line 30 from configure.ac and try again?
```
m4_rename_force([saved_AC_PROG_CC], [AC_PROG_CC])
```

If that doesn't help (or at least produces a better error), I would reocmmend to ask on the autoconf mailing list.

@hebasto it would be nice if you have a minute to check if you can reproduce this on MacOS.

**Comment by hebasto** [comment] 2021-09-12 17:42
Tested master (9a5a87e0f1276e0284446af1172056ea4693737f) on macOS Catalina 10.15.7 (19H1323) + latest `brew` packages.
```
% git clone https://github.com/bitcoin-core/secp256k1.git
% cd secp256k1
% ./autogen.sh
% ./configure
...
Build Options:
  with ecmult precomp     = yes
  with external callbacks = no
  with benchmarks         = yes
  with tests              = yes
  with openssl tests      = no
  with coverage           = no
  module ecdh             = no
  module recovery         = no
  module extrakeys        = no
  module schnorrsig       = no

  asm                     = x86_64
  ecmult window size      = 15
  ecmult gen prec. bits   = 4

  valgrind                = no
  CC                      = gcc
  CPPFLAGS                = -I/usr/local/opt/valgrind/include 
  SECP_CFLAGS             = -O2  -std=c89 -pedantic -Wno-long-long -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-overlength-strings -Wall -Wno-unused-function -Wextra -Wcast-align -Wconditional-uninitialized -fvisibility=hidden 
  CFLAGS                  = -g -O2
  LDFLAGS                 = 

  CC_FOR_BUILD            = gcc
  CPPFLAGS_FOR_BUILD      = -I/usr/local/opt/valgrind/include 
  SECP_CFLAGS_FOR_BUILD   = -O2  -std=c89 -pedantic -Wno-long-long -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-overlength-strings -Wall -Wno-unused-function -Wextra -Wcast-align -Wconditional-uninitialized -fvisibility=hidden 
  CFLAGS_FOR_BUILD        = -g -O2
  LDFLAGS_FOR_BUILD       =
```

No issues.

**Comment by hebasto** [comment] 2021-09-12 18:02
@samyuyagati 

Could you share the output of `brew list` command?

**Comment by samyuyagati** [comment] 2021-09-14 01:35
Here's the output of brew list:
autoconf	jemalloc	ocaml
automake	libev		opam
bazel		libevent	openjdk@11
bdw-gc		libffi		openssl@1.1
boost		libidn2		p11-kit
c-ares		libsodium	pkg-config
gdbm		libtasn1	python@3.9
gettext		libtool		readline
gflags		libunistring	sqlite
gmp		libuv		tbb
gnutls		m4		unbound
gpatch		mpdecimal	valgrind
guile		nettle		wget
icu4c		nghttp2		xz

I tried commenting out the m4_rename_force line, removing the generated configure script file, and rerunning autogen.sh and the new generated configure script; I get the same error.

**Comment by real-or-random** [comment] 2021-09-14 07:22
> Addendum -- if I re-clone the repository, I get the following warning while running autogen:
> 
> ```
> configure.ac:32: warning: The macro `AC_PROG_CC_C89' is obsolete.
> configure.ac:32: You should run autoupdate
> ```

Oh, this warning is intended for the maintainer, not for the user. So you shouldn't run autoupdate. (And we have reasons why we don't run it because then old versions of autoconf won't work any longer.) Have you tried
```
git clone https://github.com/bitcoin-core/secp256k1.git
cd secp256k1
./autogen.sh
./configure
```
without autoupdate?

> I just found out that if I don't rerun autogen.sh after running autoupdate, I can run the configure script to what appears to be completion; however, after that, if I run "make", I get an error with the same syntax error (newline on 13153) in the configure script that I had before -- the same error is still present, but it looks like it doesn't trigger when running configure alone, only when runnign make.

This is because make notices that ./configure should be run and then runs it, so it's no surprise that the effect is the same.

**Comment by real-or-random** [comment] 2022-02-08 21:56
Closing this for now, but feel free to reply if this is still an issue.

**Closed by real-or-random** 2022-02-08 21:56 UTC
