### ISSUE TITLE
Verifiable Random Function (VRF)

### ISSUE THREAD

**Issue by kroggen** [bitcoin-core/secp256k1#706] opened 2020-01-05 05:02 UTC
Congrats for the great repo!

Here is a suggestion:

What about an implementation of a Verifiable Random Function using the secp256k1 curve?

Having a secure VRF in this library, or as a separate code that uses this library, would be a really useful piece of code.

The Algorand team created one using the ed25519 curve and sha512 in a forked `libsodium` repo. You can check it out [here](https://github.com/algorand/libsodium/tree/draft-irtf-cfrg-vrf-03/src/libsodium/crypto_vrf)

I found implementations using secp256k1 and sha256 in other languages:

* Rust: [vrf-rs](https://github.com/witnet/vrf-rs)
* Go: [chain33](https://github.com/33cn/chain33/tree/master/common/vrf/secp256k1)
* Solidity: [vrf-solidity](https://github.com/witnet/vrf-solidity)

But none in C

The last version of IETF draft for VRFs (at this date) is [draft-irtf-cfrg-vrf-05](https://tools.ietf.org/id/draft-irtf-cfrg-vrf-05.html)

**Comment by gmaxwell** [comment] 2020-01-05 05:53
Without an extremely clear understanding of at least some relevant applications its unlikely that this library could provide an acceptable safe interface.  Otherwise this is a pretty low level primitive 

I'm not aware of any particular reason this function would be of interest to any of the regular contributors to the library.

To save other contributors time in understanding what this even is, using conventional variable names:

* There is a prover with a keypair (x, xG) and a verifier which knows the public key (xG).
* The prover takes a message and emits a proof. Anyone with the proof and message and the pubkey can extract a consistent hash.
* The proof is proof of discrete log equivalence between the pubkey and a point (H) created by hashing the pubkey and the message. The challenge hash in the DLEQ is {H,xH,message,kG,kH} -- it does not commit to the pubkey except indirectly through H, the proof is xH,s,e -- (it's in e,s form).

Use of the e,s form probably was chosen because it saves 32 bytes (otherwise you'd have to send both nonces)... but it breaks batch validation which would otherwise work. Verifying requires a hash-to-curve and two independent multiexps.

The 'random value' is not close to uniform if the attacker can choose the message with knowledge of the pubkey, or the pubkey with knowledge of the message.

**Comment by kroggen** [comment] 2020-01-05 08:55
In blockchains, VRFs can be used to prove that a generated random number is correct.

Example: selecting a node to be the next block producer without using proof-of-work.

Each node has its private/secret key and shares its public key with other nodes, so they can verify that the generated random number from a specific node is correct and it was not modified. Nodes calculate this random number using their private key and a publicly known seed, different at each round.

Using VRFs makes the process non-interactive: they do not need to exchange many messages to reach a consensus on some global random number.

**Comment by jonasnick** [comment] 2020-01-05 09:22
> In blockchains

It's not obvious from the name of this library but "the primary focus of its development has been for usage in the *Bitcoin* system" (from the README, emphasis added). I'm not aware of an application in Bitcoin-land that uses a VRF. There's the somewhat less focused [secp256k1-zkp](https://github.com/ElementsProject/secp256k1-zkp) fork where a VRF may get merged if it's behind a sane API with a clear protocol description.

**Comment by gmaxwell** [comment] 2020-01-05 16:48
It's unclear to me why a 'blockchain application' wouldn't prefer to use:

The hash of a BLS signature as it would be smaller, batch verifiable, simpler to implement from existing primitives and much easier to create a threshold random beacon (non-interactive multiparty, too).

Or an alternative construction for this which is batch verifyable but slightly larger.

Or, if proof sizes and speeds aren't much of an issue, something like purify where the 'random value' is a EC point with a prover known discrete log-- which allows using it as a nonce in a single show signature ("leak your private key if you sign more than T times for a given VRF context").

I can totally believe that this construct would be the best fit for _some_ application... but you've got to have at least one full application in mind to make a good interface.  And when I think of applications (or, rather, consider similar application's we've discussed in the past)-- other known/obvious constructions sound obviously better to me.

**Comment by kroggen** [comment] 2020-01-05 20:44
As far as I understand, batch verification is not of use in a case where there is no signature aggregation. Each selected node sends the generated random number + the proof. The receiver nodes only need to verify the proof from this single or few nodes.

It should not be single use too. Generating many random numbers should not reveal bits of the private key.

Anyway, it was just an idea of implementation of the IETF draft so it could be used in many different applications, not only on a specific use case.

**Comment by gmaxwell** [comment] 2020-01-05 23:03
For example, say you want to validate a million block history.  With scalar validation you'll be doing two multiexps per block, but with batch validation you could do one big batch with all two million at once (or more realistically groups of a moderate amount at time for engineering reasons). Signature aggregation doesn't come into it. (though this sort of thing could also be batch validated along with signatures if they were constructed using the same curve)

**Comment by real-or-random** [comment] 2020-01-06 11:16
> It's not obvious from the name of this library but "the primary focus of its development has been for usage in the _Bitcoin_ system" (from the README, emphasis added). I'm not aware of an application in Bitcoin-land that uses a VRF. There's the somewhat less focused [secp256k1-zkp](https://github.com/ElementsProject/secp256k1-zkp) fork where a VRF may get merged if it's behind a sane API with a clear protocol description.

I agree. I'm closing this because there's no need for a VRF in the Bitcoin ecosystem currently. Let me stress that does not mean that there won't be a use case in the future. But I feel confident enough to speak for the maintainers and regular contributors that there is no interest in an implementation of a VRF currentluy. Feel free to object, of course.

And please feel free to discuss this further. The fact that the issue is closed does not mean that we can't discuss further.

**Closed by real-or-random** 2020-01-06 11:16 UTC

**Comment by kroggen** [comment] 2020-01-19 06:47
For those interested, I implemented an elliptic curve based Verifiable Random Function (VRF) using a fork of this library [here](https://github.com/aergoio/secp256k1-vrf)

It is in a fork because the required functions are not exported, otherwise it could be just a code dependent of this library.

The library is compiled under a different name, so both can be present on the same device.

It is based on the [IETF VRF draft 05](https://tools.ietf.org/id/draft-irtf-cfrg-vrf-05.html)

Any review is welcome.
