### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by skywinder** [bitcoin-core/secp256k1#489] opened 2017-12-05 18:56 UTC
I'm using upgrading project, which use this library to build native iOS framework https://github.com/beyonderyue/ios-secp256k1

Can you suggest stable stash commit for using in this library?

I want to purpose to add tags to a git repo to structurize work and point for users a stable library version.

Is the 6ad5cdb42a1a8257289a0423d644dcbdeab0f83c a stable version? May I suggest to set a tag `1.0.0` for this to start versionising process?

**Comment by apoelstra** [comment] 2017-12-05 20:19
dupe of https://github.com/bitcoin-core/secp256k1/issues/286

**Closed** 2017-12-05 20:19 UTC
