### ISSUE TITLE
Simple usage example

### ISSUE THREAD

**Issue by josephernest** [bitcoin-core/secp256k1#496] opened 2018-01-08 00:56 UTC
It would be interesting to provide a simple usage example in C / C++, i.e. how to use the library on an input private key to produce an output public key, ready to be SHA256d and RIPEMD160d.

Example:

    // private key: abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234
    unsigned char private[32] = { 0xAB, 0xCD, 0x12, 0x34, 0xAB, 0xCD, 0x12, 0x34, 0xAB, 0xCD, 0x12, 0x34, 0xAB, 0xCD, 0x12, 0x34, 0xAB, 0xCD, 0x12, 0x34, 0xAB, 0xCD, 0x12, 0x34, 0xAB, 0xCD, 0x12, 0x34, 0xAB, 0xCD, 0x12, 0x34 };

    unsigned char pub[65] = ?secp256k1_pub_from_pvt?(private);   // which function to use here?
    unsigned char pub_compr[33] = ?secp256k1_pub_compr_from_pvt?(private);
    unsigned char hash160[20] = ripemd160(sha256(...));         // what is the common implementation used here?

**Comment by elichai** [comment] 2018-04-03 11:32
:+1:

**Comment by afk11** [comment] 2018-04-03 12:39
The best place to start is the header file:

Creating a context: https://github.com/bitcoin-core/secp256k1/blob/master/include/secp256k1.h#L182 
Creating a public key: https://github.com/bitcoin-core/secp256k1/blob/master/include/secp256k1.h#L518
Serialize a public key (for hashing): https://github.com/bitcoin-core/secp256k1/blob/master/include/secp256k1.h#L317

For example usage, see the tests.

**Comment by sipa** [comment] 2018-05-06 17:45
EC private keys are just random bytes.

**Comment by gmaxwell** [comment] 2019-02-20 11:17
Dupe of #184

**Closed by gmaxwell** 2019-02-20 11:17 UTC
