### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-core/secp256k1#820] opened 2020-09-18 14:49 UTC
libsecp256k1 is fairly mature these days. It seems like it would be appropriate to begin versioning the API/ABI and tagging releases.

Already, configure warns that *experimental* APIs don't have stable APIs, which implies that non-experimental features do.

If you want, I can prepare a PR to setup the necessary autotools stuff.

Also need to select an initial version number. Does 1.0 sound good?

**Comment by real-or-random** [comment] 2020-09-18 15:03
There's agreement here that we should have a tagged release soon, see the most recent comments in #286.

> If you want, I can prepare a PR to setup the necessary autotools stuff.

What would be the necessary autotools stuff?

(I'm closing this since it's essentially a duplicate of #286, feel free to reply there. )

**Closed by real-or-random** 2020-09-18 15:03 UTC

**Comment by luke-jr** [comment] 2020-09-18 19:30
Basically `-version` in LDFLAGS
