### ISSUE TITLE
CUDA Support

### ISSUE THREAD

**Issue by pv081079** [bitcoin-core/secp256k1#1589] opened 2024-08-17 18:58 UTC
There's exists a chance to add support for CUDA?

**Comment by real-or-random** [comment] 2024-08-17 20:53
This is essentially a duplicate of https://github.com/bitcoin-core/secp256k1/issues/1214. The tl;dr is: Yes, there is a non-zero chance, but no, noone is working on it and noone is planning to work on it.

**Closed by real-or-random** 2024-08-17 20:53 UTC
